# Generated by Django 5.0.6 on 2024-06-03 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0004_users_delete_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ville', models.CharField(max_length=30)),
                ('lien_map_ville', models.URLField()),
                ('logo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Offre_de_stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_stage', models.CharField(choices=[('OBS', 'Observation'), ('ASS_ENG', 'Assistant Ingenieur'), ('PFE', "Projet de fin d'étude"), ('RES', 'Recherche')], max_length=10)),
                ('ville', models.CharField(max_length=30)),
                ('RH_email', models.EmailField(max_length=254)),
                ('date_de_publication', models.DateField(auto_now_add=True)),
                ('logo_url', models.URLField()),
                ('durée', models.IntegerField(default=2)),
                ('entrprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.entreprise')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.secteur')),
            ],
        ),
        migrations.AddField(
            model_name='entreprise',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.secteur'),
        ),
    ]
