# Generated by Django 5.0.6 on 2024-06-03 20:22

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0005_entreprise_secteur_offre_de_stage_entreprise_secteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OBS', 'Observation'), ('ASS_ENG', 'Assistant Ingenieur'), ('PFE', "Projet de fin d'étude"), ('RES', 'Recherche')], max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.entreprise')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.secteur')),
            ],
        ),
        migrations.CreateModel(
            name='Alumnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('promotion', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('linkdn', models.URLField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('numero', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('emploi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emploi', to='etudiant.stage')),
                ('stage_1A', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stage_1A', to='etudiant.stage')),
                ('stage_2A', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stage_2A', to='etudiant.stage')),
                ('stage_3A', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stage_3A', to='etudiant.stage')),
            ],
        ),
    ]
