# Generated by Django 5.0.6 on 2024-06-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0006_stage_alumnis'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='lien_page_web',
            field=models.URLField(null=True),
        ),
    ]
