# Generated by Django 5.0.6 on 2024-06-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0007_entreprise_lien_page_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnis',
            name='nom',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='alumnis',
            name='prenom',
            field=models.CharField(max_length=25),
        ),
    ]
