# Generated by Django 5.0.6 on 2024-06-03 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0008_alter_alumnis_nom_alter_alumnis_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secteur',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CV', models.FileField(upload_to='')),
                ('Lettre de motivation', models.FileField(upload_to='')),
                ('Offre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='etudiant.offre_de_stage')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.users')),
            ],
        ),
    ]
