# Generated by Django 5.0.6 on 2024-06-05 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0009_alter_secteur_nom_candidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='secteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='etudiant.secteur'),
        ),
    ]
