# Generated by Django 5.0.6 on 2024-06-06 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0010_users_secteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='Offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.offre_de_stage'),
        ),
    ]
