# Generated by Django 5.0.6 on 2024-06-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0011_alter_candidature_offre'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre_de_stage',
            name='Ce_que_nous_offrons',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offre_de_stage',
            name='Missions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offre_de_stage',
            name='Profil_recherché',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offre_de_stage',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
