# Generated by Django 5.0.6 on 2024-06-08 23:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0014_s_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='S_users',
            new_name='Service_users',
        ),
    ]
