# Generated by Django 5.0.6 on 2024-06-16 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0016_alter_offre_de_stage_ce_que_nous_offrons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='etudiant.secteur'),
        ),
    ]
