# Generated by Django 5.0.6 on 2024-06-16 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0017_alter_entreprise_secteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiant.secteur'),
        ),
        migrations.AlterField(
            model_name='offre_de_stage',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiant.secteur'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiant.secteur'),
        ),
        migrations.AlterField(
            model_name='users',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiant.secteur'),
        ),
    ]
