# Generated by Django 5.0.6 on 2024-06-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0018_alter_entreprise_secteur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnis',
            name='emploi',
        ),
        migrations.RemoveField(
            model_name='alumnis',
            name='stage_1A',
        ),
        migrations.RemoveField(
            model_name='alumnis',
            name='stage_2A',
        ),
        migrations.RemoveField(
            model_name='alumnis',
            name='stage_3A',
        ),
        migrations.AddField(
            model_name='alumnis',
            name='emploi_entreprise',
            field=models.CharField(default='*', max_length=30),
        ),
        migrations.AddField(
            model_name='alumnis',
            name='emploi_secteur',
            field=models.CharField(default='*', max_length=30),
        ),
        migrations.AddField(
            model_name='alumnis',
            name='stage_1A_entreprise',
            field=models.CharField(default='*', max_length=30),
        ),
        migrations.AddField(
            model_name='alumnis',
            name='stage_1A_secteur',
            field=models.CharField(default='*', max_length=30),
        ),
        migrations.AddField(
            model_name='alumnis',
            name='stage_1A_ville',
            field=models.CharField(default='*', max_length=30),
        ),
        migrations.AddField(
            model_name='alumnis',
            name='stage_2A_entreprise',
            field=models.CharField(default='*', max_length=30),
        ),
        migrations.AddField(
            model_name='alumnis',
            name='stage_2A_secteur',
            field=models.CharField(default='*', max_length=30),
        ),
        migrations.AddField(
            model_name='alumnis',
            name='stage_2A_ville',
            field=models.CharField(default='*', max_length=30),
        ),
        migrations.AddField(
            model_name='alumnis',
            name='stage_3A_entreprise',
            field=models.CharField(default='*', max_length=30),
        ),
        migrations.AddField(
            model_name='alumnis',
            name='stage_3A_secteur',
            field=models.CharField(default='*', max_length=30),
        ),
        migrations.AddField(
            model_name='alumnis',
            name='stage_3A_ville',
            field=models.CharField(default='*', max_length=30),
        ),
    ]
