# Generated by Django 5.0.6 on 2024-06-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0020_alter_entreprise_secteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre_de_stage',
            name='entrprise',
            field=models.CharField(default='*', max_length=200),
        ),
    ]
