# Generated by Django 5.0.6 on 2024-06-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0021_alter_offre_de_stage_entrprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre_de_stage',
            name='secteur',
            field=models.CharField(default='*', max_length=200),
        ),
    ]
