# Generated by Django 5.0.6 on 2024-06-18 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0023_rh_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rh_favories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.rh_service')),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.candidature')),
            ],
        ),
    ]
