# Generated by Django 5.0.6 on 2024-06-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0024_rh_favories'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='annee_etude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
