# Generated by Django 5.0.6 on 2024-06-18 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0025_users_annee_etude_users_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('specialite', models.CharField(max_length=100)),
                ('introduction', models.TextField(blank=True)),
                ('formation', models.TextField(blank=True)),
                ('experiences_professionnelles', models.TextField(blank=True)),
                ('competences_techniques', models.TextField(blank=True)),
                ('soft_skills', models.TextField(blank=True)),
                ('projets_realises', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('publications', models.TextField(blank=True)),
                ('activites_extrascolaires', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
