# Generated by Django 5.0.6 on 2024-06-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0026_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnis',
            name='emploi_ville',
            field=models.CharField(default='*', max_length=30),
        ),
    ]
